### ISSUE TITLE
Found a bug in the code

### ISSUE THREAD

**Issue by sriniAzureDevops** [sriniAzureDevops/DevOps#1]
Hi Team,

Found a bug in the code, please fix.

**Comment by bipeensinha** [comment]
Hi Sir, This is going to resolved
![Uploading a.png…]()

**Comment by sriniAzureDevops** [comment]
![bug](https://user-images.githubusercontent.com/85954621/122090003-ed1c2800-cdcc-11eb-85cc-5b2b50b96110.PNG)
Thank you close the issue

**Comment by bipeensinha** [comment]
thakns
